### PR TITLE
[Bug: 1379] Added Multimodal support for Milvus for retriever component

### LINKED ISSUE #1379: [Feature]Add Multimodal support for Milvus retriever
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Running nodes

Single Node

### Description

Add enhancement to support Multimodality in Milvus retriever

### PR DESCRIPTION
**Pull request by srajabos**
Fixes #1379

## Description

Added Multimodal support for Milvus for retriever component

## Issues

https://github.com/opea-project/GenAIComps/issues/1379

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ *] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [* ] Others (enhancement, documentation, validation, etc.)

## Dependencies

na

### CODE REVIEW

**Comment by xiguiw** [comment]
@srajabos  The CI failed.
Please check if there is typo of the container name.

+ HTTP_STATUS=000
+ '[' 000 -eq 200 ']'
+ echo '[ retriever ] HTTP status is not 200. Received status was 000'
+ docker logs retriever-milvus
[ retriever ] HTTP status is not 200. Received status was 000
Error response from daemon: No such container: retriever-milvus
+ exit 1

**Comment by pallavijaini0525** [comment]
@xiguiw  -> Not able to reproduce the issue locally, but updated the test to include multimodal

**Comment by chensuyue** [comment]
Please clean up the commit history.

**Comment by pallavijaini0525** [comment]
@chensuyue  -> Looks like branch is rebased on March 14th, please help me understand how to clean up commit history?

**Comment by pallavijaini0525** [comment]
retriever_neo4j and retriever_opensearch are failing and not related to our changes

**Comment by pallavijaini0525** [comment]
@xiguiw @chensuyue  -> All tests are passed, please help in merging this PR.

**Review by chensuyue — APPROVED** [review]

**Comment by chensuyue** [comment]
@lkk12014402 @lvliang-intel please review.

File: tests/retrievers/test_retrievers_milvus.sh [hunk 1]
```diff
@@ -71,12 +89,56 @@ function validate_microservice() {
...
+        exit 1
+    fi
+}
+
 function stop_docker() {
     cd $WORKPATH/comps/third_parties/milvus/deployment/docker_compose/
     docker compose -f compose.yaml down --remove-orphans
 
+    docker stop milvus-etcd
+    docker rm milvus-etcd
```
Comment (letonghan) [inline tests/retrievers/test_retrievers_milvus.sh:136]: why only the milvus-etcd is stopped and deleted? these operations should also be done for milvus-minio and milvus-standalone

Comment (jainipallavi102210) [reply tests/retrievers/test_retrievers_milvus.sh:136]: docker compose -f compose.yaml down --remove-orphans is deleting all other containers, i see some issues with etcd deletion, so i have explicitly added to avoid the issues.

**Comment by xiguiw** [comment]
@srajabos 
The branch has conflicts. Please resolve the conflicts. Thanks!

**Comment by srajabos** [comment]
@xiguiw - resolved conflicts- thanks

**Comment by srajabos** [comment]
@xiguiw  - kindly update what is required to get this PR merged

**Review by letonghan — APPROVED** [review]

**Comment by xiguiw** [comment]
@srajabos  @pallavijaini0525 

CI passed. (retrievers_redis, intel-cpu)  is a known issue.

Please rebase the branch, there is confilcts.

**Comment by jainipallavi102210** [comment]
@xiguiw  -> No conflicts are present, it can be merged.
